// PDF Download Utility for Interview Results
// Downloads as HTML file that can be printed or converted to PDF

export const downloadInterviewResults = async (results: any, filename: string = 'interview-results.html') => {
  try {
    // Create HTML content
    const htmlContent = generateReportHTML(results);
    
    // Create blob with proper filename
    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
    
    // Create download link
    const link = document.createElement('a');
    const url = window.URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename.replace('.pdf', '.html'));
    link.style.visibility = 'hidden';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up
    window.URL.revokeObjectURL(url);
    
    return true;
  } catch (error) {
    console.error('Failed to generate report:', error);
    // Fallback: download as JSON
    downloadResultsJSON(results, filename.replace('.pdf', '.json'));
    return false;
  }
};

function generateReportHTML(results: any): string {
  const perQuestion = results.perQuestionEvaluations || results.per_question || [];
  
  const questionsHTML = perQuestion.map((item: any, idx: number) => {
    const questionText = item.question?.question || item.question?.text || '';
    const company = item.question?.company || 'General';
    const score = item.score || 0;
    const strengths = (item.strengths || []).map((s: string) => `<li>${s}</li>`).join('');
    const weaknesses = (item.weaknesses || []).map((w: string) => `<li>${w}</li>`).join('');
    const feedback = item.feedback || '';
    
    return `
      <div style="page-break-inside: avoid; margin: 20px 0; border: 1px solid #ddd; padding: 15px;">
        <h3>Q${idx + 1}: ${company}</h3>
        <p><strong>Question:</strong> ${questionText}</p>
        <p><strong>Score:</strong> <span style="color: #4CAF50; font-weight: bold;">${score}/100</span></p>
        ${strengths ? `<div><strong>Strengths:</strong><ul>${strengths}</ul></div>` : ''}
        ${weaknesses ? `<div><strong>Areas for Improvement:</strong><ul>${weaknesses}</ul></div>` : ''}
        ${feedback ? `<div><strong>Feedback:</strong> ${feedback}</div>` : ''}
      </div>
    `;
  }).join('');
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Interview Performance Report</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
        h1 { color: #0066cc; text-align: center; }
        h2 { color: #333; margin-top: 30px; }
        .header { text-align: center; margin-bottom: 30px; }
        .score-box { background: #f0f0f0; padding: 20px; border-radius: 5px; text-align: center; margin: 20px 0; }
        .score-box h2 { margin: 0; color: #0066cc; }
        ul { margin: 10px 0; }
        li { margin: 5px 0; }
        @media print { body { margin: 0; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>📋 Interview Performance Report</h1>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
      </div>
      
      <div class="score-box">
        <h2>Overall Score: ${results.overallScore || results.overall_score || 0}/100</h2>
      </div>
      
      <h2>Question-wise Analysis</h2>
      ${questionsHTML}
      
      <p style="margin-top: 40px; text-align: center; color: #999; font-size: 12px;">
        Generated by PM Bot Interview Platform
      </p>
    </body>
    </html>
  `;
}

// Download as JSON
export const downloadResultsJSON = (results: any, filename: string = 'interview-results.json') => {
  try {
    const dataStr = JSON.stringify(results, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,' + encodeURIComponent(dataStr);
    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', filename);
    linkElement.click();
    return true;
  } catch (error) {
    console.error('Failed to download JSON:', error);
    return false;
  }
};

// Download as CSV
export const downloadResultsCSV = (results: any, filename: string = 'interview-results.csv') => {
  try {
    let csv = 'Question #,Company,Category,Score,Strengths,Weaknesses,Feedback\n';
    
    if (results.per_question && Array.isArray(results.per_question)) {
      results.per_question.forEach((item: any, index: number) => {
        const company = item.question?.company || 'General';
        const category = item.question?.category || 'General';
        const score = item.score || 0;
        const strengths = (item.strengths || []).join('; ').replace(/"/g, '""');
        const weaknesses = (item.weaknesses || []).join('; ').replace(/"/g, '""');
        const feedback = (item.feedback || '').replace(/"/g, '""');
        
        csv += `"Q${index + 1}","${company}","${category}","${score}","${strengths}","${weaknesses}","${feedback}"\n`;
      });
    }
    
    const dataUri = 'data:text/csv;charset=utf-8,' + encodeURIComponent(csv);
    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', filename);
    linkElement.click();
    return true;
  } catch (error) {
    console.error('Failed to generate CSV:', error);
    return false;
  }
};
