// Share Results Utility
import { InterviewResult } from '../types';

export interface ShareOptions {
  title: string;
  summary: string;
  score: number;
  url: string;
}

export const getShareOptions = (result: InterviewResult): ShareOptions => {
  const score = result.overallScore || 0;
  const summary = `I scored ${score}/100 on a PM interview! 🎯`;
  const title = 'PM Interview Results';
  
  // Create shareable URL (in production, this would be a link to view results)
  const url = `${window.location.origin}${window.location.pathname}`;
  
  return { title, summary, score, url };
};

export const shareViaEmail = (result: InterviewResult) => {
  const options = getShareOptions(result);
  const skillsList = result.skillScores
    .map(s => `${s.skill}: ${s.score}/100`)
    .join('\n');
  
  const body = encodeURIComponent(
    `I just completed a PM interview assessment!\n\n` +
    `Overall Score: ${options.score}/100\n\n` +
    `Skills Breakdown:\n${skillsList}\n\n` +
    `Check out the PM Bot Interview Platform to practice: ${options.url}`
  );
  
  const mailto = `mailto:?subject=${encodeURIComponent(options.title)}&body=${body}`;
  window.location.href = mailto;
};

export const shareViaLinkedIn = (result: InterviewResult) => {
  const options = getShareOptions(result);
  const linkedInUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(options.url)}`;
  window.open(linkedInUrl, '_blank');
};

export const shareViaTwitter = (result: InterviewResult) => {
  const options = getShareOptions(result);
  const text = encodeURIComponent(
    `${options.summary} Learning PM with @PMBotApp. ` +
    `Check out interview practice platform!`
  );
  
  const twitterUrl = `https://twitter.com/intent/tweet?text=${text}&url=${encodeURIComponent(options.url)}`;
  window.open(twitterUrl, '_blank', 'width=550,height=420');
};

export const copyShareLink = (result: InterviewResult) => {
  const options = getShareOptions(result);
  const shareText = `${options.summary}\n\nVisit: ${options.url}`;
  
  navigator.clipboard.writeText(shareText).then(() => {
    alert('Results link copied to clipboard!');
  }).catch(() => {
    alert('Failed to copy link. Please try again.');
  });
};

export const shareResultsAsText = (result: InterviewResult): string => {
  const skillsList = result.skillScores
    .map(s => `• ${s.skill}: ${s.score}/100`)
    .join('\n');
  
  const strengths = result.strengths?.join(', ') || 'N/A';
  const improvements = result.improvements?.join(', ') || 'N/A';
  
  return (
    `PM INTERVIEW RESULTS\n` +
    `${'='.repeat(50)}\n\n` +
    `Overall Score: ${result.overallScore}/100\n\n` +
    `Skills:\n${skillsList}\n\n` +
    `Strengths: ${strengths}\n\n` +
    `Areas for Improvement: ${improvements}\n\n` +
    `Generated by PM Bot Interview Platform`
  );
};
